apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:20.0.1
        resources: {}
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: postgres
        - name: KC_DB_USERNAME
          value: admin
        - name: KC_DB_PASSWORD
          value: psltest
        - name: KC_DB_URL_PORT
          value: '5432'
