---
apiVersion: v2
name: argo-cd
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
type: application
version: 1.0.0
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
sources:
  - https://argoproj.github.io/argo-helm
dependencies:
  - name: argo-cd
    version: 5.16.1
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 0.0.8
    repository: https://argoproj.github.io/argo-helm
