apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    name: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/GabrielBrotas/meetup-microservices
    targetRevision: HEAD
    path: infrastructure/modules/argo-cd
    helm:
      values: |
        argocd-apps:
          applications:
            - name: app-of-apps
              project: default
              namespace: argocd
              destination:
                name: in-cluster
                namespace: argocd
              source:
                repoURL: https://github.com/GabrielBrotas/meetup-microservices
                path: infrastructure/app-of-apps/local
                targetRevision: main
              syncPolicy:
                automated:
                  prune: true
                  selfHeal: true

  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true