apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meetup-meetings
  namespace: argocd
  labels:
    name: meetup-meetings
spec:
  project: default

  source:
    repoURL: https://github.com/GabrielBrotas/meetup-microservices
    targetRevision: HEAD
    path: microservices/meetings/k8s/overlays/local

    kustomize:
      commonLabels:
        project: meetup

  destination:
    name: in-cluster
    namespace: meetings

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
