apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
 variant: local
commonAnnotations:
  note: “Welcome to local server!”

bases:
- ../../base

resources:
- ./db.yaml

patchesStrategicMerge:
- deployment.yaml

