apiVersion: v1
kind: Service
metadata:
  name: categories-svc
spec:
  selector:
    app: meetup-categories
  type: NodePort
  ports:
    - name: http
      port: 4001
      targetPort: 4001
      protocol: TCP