apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-auth
  namespace: auth
  labels:
    app: meetup-auth
    project: meetup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-auth
  template:
    metadata:
      labels:
        app: meetup-auth
    spec:
      containers:
      - name: meetup-auth
        image: gbrotas/meetup-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources: {}