apiVersion: v1
kind: Service
metadata:
  name: meetings-svc

spec:
  selector:
    app: meetup-meetings
  
  type: NodePort
  ports:
    - name: meetings-svc
      port: 4002
      targetPort: 4002
      protocol: TCP