kafka:
  persistence:
    enabled: false

  externalAccess:
    enabled: true

  zookeeper:
    persistence:
      enabled: false

  containerPorts:
    client:	9092
    internal:	9093
    external: 9094