argo-apps:
  applications:
    - name: app-of-apps
      project: default
      namespace: argocd
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        repoURL: https://github.com/GabrielBrotas/meetup-microservices
        path: infrastructure/modules/argocd/apps
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
